[package]
name = "lwpkt_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = "2.5.0"

[features]
flags = []

[build-dependencies]
bindgen = "0.72.*"
cc = {version = "1.0.*", features = ["parallel"] }

